[package]
name = "five-words"
version = "0.1.0"
edition = "2021"
authors = ["Toon Spin"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.2.17", features = ["derive"] }
indicatif = "0.17.0"
