[package]
name = "five-words"
version = "1.0.0"
edition = "2021"
authors = ["Toon Spin"]

[dependencies]
clap = { version = "3.2.17", features = ["derive", "wrap_help"] }
indicatif = { version = "0.17.0", features = ["rayon"] }
rayon = "1.5.3"
